Remove PaaS specific event triggers after restore
These event triggers were added by default by rds broker postgres
superuser:
https://github.com/alphagov/paas-rds-broker/blob/2110a1843566653d91f26d6fdfcc6d018a331c29/sqlengine/postgres_engine.go

They are not used on Azure and they cause issues when running rails migrations, such as:

```
== 20230214083343 AddSignedUpForAdviserToApplicationForms: migrating ==========
-- add_column(:application_forms, :signed_up_for_adviser, :boolean, {:default=>false})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedObject: ERROR:  role "rdsbroker_f2792244_770f_4c01_9bbc_ac057b9087ee_manager" does not exist
CONTEXT:  PL/pgSQL function forbid_ddl_reader() line 15 at IF
/app/db/migrate/20230214083343_add_signed_up_for_adviser_to_application_forms.rb:3:in `change'
/app/lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake:5:in `block (3 levels) in <top (required)>'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  role "rdsbroker_f2792244_770f_4c01_9bbc_ac057b9087ee_manager" does not exist
CONTEXT:  PL/pgSQL function forbid_ddl_reader() line 15 at IF
/app/db/migrate/20230214083343_add_signed_up_for_adviser_to_application_forms.rb:3:in `change'
/app/lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake:5:in `block (3 levels) in <top (required)>'

Caused by:
PG::UndefinedObject: ERROR:  role "rdsbroker_f2792244_770f_4c01_9bbc_ac057b9087ee_manager" does not exist
CONTEXT:  PL/pgSQL function forbid_ddl_reader() line 15 at IF
/app/db/migrate/20230214083343_add_signed_up_for_adviser_to_application_forms.rb:3:in `change'
/app/lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake:5:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:migrate
```