[2107] Fix maintenance page (#9967)
## Context
Multiple failures:

https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/11474019248
Makefile:132: *** Missing CONFIRM_PRODUCTION=yes.  Stop.

./maintenance_page/scripts/failover.sh: line 9: MAINTENANCE_IMAGE_TAG:
unbound variable
make: *** [maintenance-fail-over] Error 1

ERROR: The subscription of 's189-teacher-services-cloud-production'
doesn't exist in cloud 'AzureCloud'.

## Changes proposed in this pull request
- Skip confirm production in workflows
- Fix environment names in workflows
- Update docs

## Guidance to review
- Review documentation
- Test in QA
- Test in production during a real maintenance