Replaced or assertions in spec file
Calling `or` after the `have_curren_path` was causing an error.

```
NoMethodError:
       undefined method `or' for an instance of Capybara::RSpecMatchers::Matchers::HaveCurrentPath
```